name: Lint and Test

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      
      - name: Install dependencies
        run: npm install

      - name: run linter
        run: make lint

      - name: run jest
        run: npx jest --coverage